const mongoose = require('mongoose');
const User = require('./models/User');
const Trip = require('./models/Trip');
const JournalEntry = require('./models/JournalEntry');
const Favorite = require('./models/Favorite');
const dotenv = require('dotenv');

dotenv.config();

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/wayfarer';

async function seed() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log('--- CONNECTED TO DB FOR MASSIVE SEEDING ---');

    await User.deleteMany({});
    await Trip.deleteMany({});
    await JournalEntry.deleteMany({});
    await Favorite.deleteMany({});
    console.log('--- CLEARED ALL COLLECTIONS ---');

    // =============================================
    // 1. Create Users (7 users for realistic data)
    // =============================================
    const users = await User.create([
      {
        name: 'Sarah Jenkins',
        email: 'admin@wayfarer.com',
        password: 'password123',
        role: 'admin',
        homeCurrency: 'USD',
        homeCountry: 'US',
        isActive: true,
        visitedCountries: ['US', 'GB', 'FR', 'JP', 'ID', 'AU', 'TH', 'SG'],
        totalTrips: 12,
        emergencyContacts: [
          { name: 'Robert Jenkins', relationship: 'Father', phone: '+1555010203' },
          { name: 'Amy Jenkins', relationship: 'Sister', phone: '+1555040506' },
        ]
      },
      {
        name: 'Marcus Thorne',
        email: 'user@wayfarer.com',
        password: 'password123',
        role: 'user',
        homeCurrency: 'USD',
        homeCountry: 'ID',
        isActive: true,
        visitedCountries: ['ID', 'JP', 'US', 'AU', 'CH', 'SG', 'TH'],
        totalTrips: 8,
        emergencyContacts: [
          { name: 'Elena Thorne', relationship: 'Sister', phone: '+628123456789' },
          { name: 'David Thorne', relationship: 'Father', phone: '+628987654321' },
        ]
      },
      {
        name: 'Yuki Sato',
        email: 'yuki@example.com',
        password: 'password123',
        role: 'user',
        homeCurrency: 'JPY',
        homeCountry: 'JP',
        isActive: true,
        visitedCountries: ['JP', 'KR', 'US', 'FR', 'IT'],
        totalTrips: 6,
        emergencyContacts: [{ name: 'Takeshi Sato', relationship: 'Brother', phone: '+81901234567' }]
      },
      {
        name: 'Alex Rivera',
        email: 'alex@example.com',
        password: 'password123',
        role: 'user',
        homeCurrency: 'EUR',
        homeCountry: 'ES',
        isActive: true,
        visitedCountries: ['ES', 'PT', 'FR', 'IT', 'DE', 'GR', 'MA'],
        totalTrips: 10,
        emergencyContacts: [{ name: 'Maria Rivera', relationship: 'Mother', phone: '+34612345678' }]
      },
      {
        name: 'Emma Watson',
        email: 'emma@example.com',
        password: 'password123',
        role: 'user',
        homeCurrency: 'GBP',
        homeCountry: 'GB',
        isActive: true,
        visitedCountries: ['GB', 'FR', 'NL', 'BE', 'DE'],
        totalTrips: 5
      },
      {
        name: 'Priya Patel',
        email: 'priya@example.com',
        password: 'password123',
        role: 'user',
        homeCurrency: 'INR',
        homeCountry: 'IN',
        isActive: true,
        visitedCountries: ['IN', 'SG', 'TH', 'MY', 'AE'],
        totalTrips: 4,
        emergencyContacts: [{ name: 'Raj Patel', relationship: 'Husband', phone: '+919876543210' }]
      },
      {
        name: 'Chen Wei',
        email: 'chen@example.com',
        password: 'password123',
        role: 'user',
        homeCurrency: 'CNY',
        homeCountry: 'CN',
        isActive: false, // Inactive user for admin testing
        visitedCountries: ['CN', 'JP', 'KR'],
        totalTrips: 2
      },
    ]);

    const [sarah, marcus, yuki, alex, emma, priya, chen] = users;
    console.log('--- 7 USERS CREATED ---');

    // =============================================
    // 2. Create Rich Trips (15+ trips across users)
    // =============================================
    const trips = await Trip.create([
      // === Marcus's Trips ===
      {
        userId: marcus._id,
        destination: 'Bali, Indonesia',
        countryCode: 'ID',
        countryName: 'Indonesia',
        startDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
        endDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
        partySize: 2,
        status: 'active',
        coverImage: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4',
        budget: { amount: 3000, currency: 'USD' },
        destinationInfo: { currency: 'IDR', language: 'Indonesian', timezone: 'Asia/Makassar', capital: 'Jakarta', population: 273523621, flagUrl: 'https://flagcdn.com/w320/id.png' },
        checklist: [
          { item: 'Vaccination certificate', category: 'health', checked: true, autoGenerated: true },
          { item: 'Offline Maps downloaded', category: 'documents', checked: true, autoGenerated: true },
          { item: 'Power adapter (Type C/F)', category: 'packing', checked: false, autoGenerated: true },
          { item: 'Travel insurance policy', category: 'documents', checked: true, autoGenerated: true },
          { item: 'Sunscreen SPF 50+', category: 'packing', checked: false, autoGenerated: true },
          { item: 'Indonesian Rupiah cash', category: 'finance', checked: true, autoGenerated: true },
          { item: 'Snorkel gear', category: 'packing', checked: false, autoGenerated: true },
          { item: 'Passport copy (digital)', category: 'documents', checked: true, autoGenerated: true },
          { item: 'Check visa requirements', category: 'visa', checked: true, autoGenerated: true },
          { item: 'Anti-malaria medication', category: 'health', checked: false, autoGenerated: true },
          { item: 'Waterproof phone case', category: 'packing', checked: true, autoGenerated: true },
          { item: 'Book surf lesson', category: 'other', checked: false, autoGenerated: false },
        ]
      },
      {
        userId: marcus._id,
        destination: 'Tokyo, Japan',
        countryCode: 'JP',
        countryName: 'Japan',
        startDate: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
        endDate: new Date(Date.now() + 32 * 24 * 60 * 60 * 1000),
        partySize: 1,
        status: 'planning',
        coverImage: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf',
        budget: { amount: 5000, currency: 'USD' },
        destinationInfo: { currency: 'JPY', language: 'Japanese', timezone: 'Asia/Tokyo', capital: 'Tokyo', population: 125800000, flagUrl: 'https://flagcdn.com/w320/jp.png' },
        checklist: [
          { item: 'Check passport validity (6+ months)', category: 'documents', checked: true, autoGenerated: true },
          { item: 'Get Japan Rail Pass', category: 'other', checked: false, autoGenerated: false },
          { item: 'Download offline Japanese phrases', category: 'other', checked: false, autoGenerated: true },
          { item: 'Pack power adapter Type A/B', category: 'packing', checked: false, autoGenerated: true },
          { item: 'Exchange to Japanese Yen', category: 'finance', checked: false, autoGenerated: true },
          { item: 'Book sumo wrestling tickets', category: 'other', checked: false, autoGenerated: false },
        ]
      },
      {
        userId: marcus._id,
        destination: 'Swiss Alps, Switzerland',
        countryCode: 'CH',
        countryName: 'Switzerland',
        startDate: new Date(Date.now() + 120 * 24 * 60 * 60 * 1000),
        endDate: new Date(Date.now() + 127 * 24 * 60 * 60 * 1000),
        partySize: 2,
        status: 'planning',
        coverImage: 'https://images.unsplash.com/photo-1531310197839-ccf54634509e',
        budget: { amount: 8000, currency: 'USD' },
        destinationInfo: { currency: 'CHF', language: 'German', timezone: 'Europe/Zurich', capital: 'Bern', population: 8654622, flagUrl: 'https://flagcdn.com/w320/ch.png' },
      },
      {
        userId: marcus._id,
        destination: 'New York City, USA',
        countryCode: 'US',
        countryName: 'United States',
        startDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000),
        endDate: new Date(Date.now() - 25 * 24 * 60 * 60 * 1000),
        partySize: 1,
        status: 'completed',
        coverImage: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9',
        budget: { amount: 2000, currency: 'USD' },
        destinationInfo: { currency: 'USD', language: 'English', timezone: 'America/New_York', capital: 'Washington D.C.', population: 331002651, flagUrl: 'https://flagcdn.com/w320/us.png' },
        checklist: [
          { item: 'Check passport validity', category: 'documents', checked: true, autoGenerated: true },
          { item: 'Broadway show tickets', category: 'other', checked: true, autoGenerated: false },
          { item: 'MetroCard', category: 'other', checked: true, autoGenerated: false },
          { item: 'Pack winter coat', category: 'packing', checked: true, autoGenerated: true },
        ]
      },
      {
        userId: marcus._id,
        destination: 'Sydney, Australia',
        countryCode: 'AU',
        countryName: 'Australia',
        startDate: new Date(Date.now() + 60 * 24 * 60 * 60 * 1000),
        endDate: new Date(Date.now() + 70 * 24 * 60 * 60 * 1000),
        partySize: 3,
        status: 'planning',
        coverImage: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9',
        budget: { amount: 4000, currency: 'USD' },
        destinationInfo: { currency: 'AUD', language: 'English', timezone: 'Australia/Sydney', capital: 'Canberra', population: 25687041, flagUrl: 'https://flagcdn.com/w320/au.png' },
      },
      {
        userId: marcus._id,
        destination: 'Bangkok, Thailand',
        countryCode: 'TH',
        countryName: 'Thailand',
        startDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000),
        endDate: new Date(Date.now() - 55 * 24 * 60 * 60 * 1000),
        partySize: 2,
        status: 'completed',
        coverImage: 'https://images.unsplash.com/photo-1563492065599-3520f775eeed',
        budget: { amount: 1500, currency: 'USD' },
        destinationInfo: { currency: 'THB', language: 'Thai', timezone: 'Asia/Bangkok', capital: 'Bangkok', population: 69799978, flagUrl: 'https://flagcdn.com/w320/th.png' },
      },

      // === Sarah's Trips ===
      {
        userId: sarah._id,
        destination: 'Paris, France',
        countryCode: 'FR',
        countryName: 'France',
        startDate: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
        endDate: new Date(Date.now() + 17 * 24 * 60 * 60 * 1000),
        partySize: 2,
        status: 'planning',
        coverImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34',
        budget: { amount: 6000, currency: 'USD' },
        destinationInfo: { currency: 'EUR', language: 'French', timezone: 'Europe/Paris', capital: 'Paris', population: 67390000, flagUrl: 'https://flagcdn.com/w320/fr.png' },
      },
      {
        userId: sarah._id,
        destination: 'London, United Kingdom',
        countryCode: 'GB',
        countryName: 'United Kingdom',
        startDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
        endDate: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
        partySize: 1,
        status: 'completed',
        coverImage: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad',
        budget: { amount: 3500, currency: 'USD' },
        destinationInfo: { currency: 'GBP', language: 'English', timezone: 'Europe/London', capital: 'London', population: 67886011, flagUrl: 'https://flagcdn.com/w320/gb.png' },
      },

      // === Yuki's Trips ===
      {
        userId: yuki._id,
        destination: 'Seoul, South Korea',
        countryCode: 'KR',
        countryName: 'South Korea',
        startDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
        endDate: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000),
        partySize: 1,
        status: 'planning',
        coverImage: 'https://images.unsplash.com/photo-1534274867514-d5b47ef89ed7',
        budget: { amount: 2000, currency: 'JPY' },
      },

      // === Alex's Trips ===
      {
        userId: alex._id,
        destination: 'Marrakech, Morocco',
        countryCode: 'MA',
        countryName: 'Morocco',
        startDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
        endDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
        partySize: 2,
        status: 'active',
        coverImage: 'https://images.unsplash.com/photo-1489749798305-4fea3ae63d43',
        budget: { amount: 2500, currency: 'EUR' },
      },
      {
        userId: alex._id,
        destination: 'Rome, Italy',
        countryCode: 'IT',
        countryName: 'Italy',
        startDate: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000),
        endDate: new Date(Date.now() - 85 * 24 * 60 * 60 * 1000),
        partySize: 1,
        status: 'completed',
        coverImage: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5',
        budget: { amount: 1800, currency: 'EUR' },
      },

      // === Priya's Trips ===
      {
        userId: priya._id,
        destination: 'Singapore',
        countryCode: 'SG',
        countryName: 'Singapore',
        startDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
        endDate: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
        partySize: 4,
        status: 'planning',
        coverImage: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd',
        budget: { amount: 150000, currency: 'INR' },
      },
      {
        userId: priya._id,
        destination: 'Dubai, UAE',
        countryCode: 'AE',
        countryName: 'United Arab Emirates',
        startDate: new Date(Date.now() - 20 * 24 * 60 * 60 * 1000),
        endDate: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000),
        partySize: 2,
        status: 'completed',
        coverImage: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c',
        budget: { amount: 200000, currency: 'INR' },
      },

      // === Emma's Trip ===
      {
        userId: emma._id,
        destination: 'Amsterdam, Netherlands',
        countryCode: 'NL',
        countryName: 'Netherlands',
        startDate: new Date(Date.now() + 40 * 24 * 60 * 60 * 1000),
        endDate: new Date(Date.now() + 45 * 24 * 60 * 60 * 1000),
        partySize: 2,
        status: 'planning',
        coverImage: 'https://images.unsplash.com/photo-1534351590666-13e3e96b5017',
        budget: { amount: 2500, currency: 'GBP' },
      },
    ]);
    console.log(`--- ${trips.length} TRIPS CREATED ---`);

    // =============================================
    // 3. Create Rich Journal Entries (12+ entries)
    // =============================================
    await JournalEntry.create([
      // Marcus - Bali
      {
        userId: marcus._id,
        tripId: trips[0]._id,
        title: 'Sunset at Tanah Lot',
        note: 'The most beautiful sunset I have ever seen. The temple looks surreal against the orange sky. The waves crashing on the rocks added to the dramatic atmosphere. I sat there for over an hour just watching.',
        location: { lat: -8.6212, lng: 115.0868, name: 'Tanah Lot Temple', country: 'Indonesia' },
        mood: 'amazing',
        weather: { temp: 27, description: 'Golden Hour', icon: '01d' },
        photos: [
          { url: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2', caption: 'Tanah Lot at golden hour' },
          { url: 'https://images.unsplash.com/photo-1555400038-63f5ba517a47', caption: 'Temple silhouette' },
        ],
        distanceTraveled: 45,
      },
      {
        userId: marcus._id,
        tripId: trips[0]._id,
        title: 'Ubud Monkey Forest',
        note: 'Watch your glasses! One monkey tried to steal my sunglasses. Very clever creatures. The ancient temple inside the forest is stunning.',
        location: { lat: -8.5188, lng: 115.2585, name: 'Sacred Monkey Forest Sanctuary', country: 'Indonesia' },
        mood: 'happy',
        weather: { temp: 28, description: 'Partly Cloudy', icon: '02d' },
        photos: [{ url: 'https://images.unsplash.com/photo-1552611052-33e04de081de', caption: 'Playful monkey' }],
        distanceTraveled: 12,
      },
      {
        userId: marcus._id,
        tripId: trips[0]._id,
        title: 'Surfing at Canggu',
        note: 'Caught my first wave today! Exhausted but finally understand the hype. The sunset from the beach bar afterward was the cherry on top.',
        location: { lat: -8.6478, lng: 115.1385, name: 'Canggu Beach', country: 'Indonesia' },
        mood: 'happy',
        weather: { temp: 29, description: 'Sunny', icon: '01d' },
        distanceTraveled: 18,
      },
      {
        userId: marcus._id,
        tripId: trips[0]._id,
        title: 'Tegallalang Rice Terraces',
        note: 'The iconic rice terraces are even more breathtaking in person. The green cascading steps are a photographer\'s paradise. Worth waking up early to beat the crowds.',
        location: { lat: -8.4312, lng: 115.2798, name: 'Tegallalang', country: 'Indonesia' },
        mood: 'amazing',
        weather: { temp: 26, description: 'Morning Mist', icon: '50d' },
        photos: [{ url: 'https://images.unsplash.com/photo-1531973576160-7125cd663d86', caption: 'Morning at the terraces' }],
        distanceTraveled: 35,
      },

      // Marcus - New York
      {
        userId: marcus._id,
        tripId: trips[3]._id,
        title: 'Central Park in Autumn',
        note: 'The fall colors in Central Park are stunning. Grabbed a hot dog from a street vendor and just people-watched near Bethesda Fountain.',
        location: { lat: 40.7812, lng: -73.9665, name: 'Central Park', country: 'United States' },
        mood: 'happy',
        weather: { temp: 15, description: 'Partly Cloudy', icon: '03d' },
        photos: [{ url: 'https://images.unsplash.com/photo-1534430480872-3498386e7856', caption: 'Bethesda Fountain' }],
        distanceTraveled: 8,
      },
      {
        userId: marcus._id,
        tripId: trips[3]._id,
        title: 'Broadway: Hamilton!',
        note: 'Saw Hamilton on Broadway! The performance was incredible, worth every penny. The energy in the theater was electric.',
        location: { lat: 40.7580, lng: -73.9855, name: 'Richard Rodgers Theatre', country: 'United States' },
        mood: 'amazing',
        photos: [{ url: 'https://images.unsplash.com/photo-1583643763660-310168be4527', caption: 'Times Square at night' }],
        distanceTraveled: 3,
      },
      {
        userId: marcus._id,
        tripId: trips[3]._id,
        title: 'Top of the Rock',
        note: 'The view from the observation deck is absolutely incredible. You can see the entire Manhattan skyline, Central Park, and even the Statue of Liberty on the horizon.',
        location: { lat: 40.7593, lng: -73.9794, name: 'Rockefeller Center', country: 'United States' },
        mood: 'amazing',
        weather: { temp: 12, description: 'Clear Sky', icon: '01d' },
        distanceTraveled: 2,
      },

      // Marcus - Bangkok
      {
        userId: marcus._id,
        tripId: trips[5]._id,
        title: 'Grand Palace Wonder',
        note: 'The Grand Palace is absolutely magnificent. The intricate details on every building are mind-blowing. The Emerald Buddha temple was the highlight.',
        location: { lat: 13.7500, lng: 100.4913, name: 'Grand Palace', country: 'Thailand' },
        mood: 'amazing',
        weather: { temp: 33, description: 'Hot & Humid', icon: '01d' },
        photos: [{ url: 'https://images.unsplash.com/photo-1563492065599-3520f775eeed', caption: 'Grand Palace spires' }],
        distanceTraveled: 15,
      },

      // Sarah - London
      {
        userId: sarah._id,
        tripId: trips[7]._id,
        title: 'Tower Bridge at Dusk',
        note: 'Walked across Tower Bridge as the sun was setting. The reflections on the Thames were magical. London never ceases to amaze me.',
        location: { lat: 51.5055, lng: -0.0754, name: 'Tower Bridge', country: 'United Kingdom' },
        mood: 'happy',
        weather: { temp: 11, description: 'Overcast', icon: '04d' },
        photos: [{ url: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad', caption: 'Tower Bridge sunset' }],
        distanceTraveled: 10,
      },

      // Alex - Morocco
      {
        userId: alex._id,
        tripId: trips[9]._id,
        title: 'Lost in the Medina',
        note: 'Spent three hours getting beautifully lost in the labyrinthine streets of the Marrakech Medina. The colors, smells, and sounds are overwhelming in the best way.',
        location: { lat: 31.6295, lng: -7.9811, name: 'Medina of Marrakech', country: 'Morocco' },
        mood: 'happy',
        weather: { temp: 28, description: 'Sunny', icon: '01d' },
        photos: [{ url: 'https://images.unsplash.com/photo-1489749798305-4fea3ae63d43', caption: 'Vibrant Medina streets' }],
        distanceTraveled: 6,
      },

      // Priya - Dubai
      {
        userId: priya._id,
        tripId: trips[12]._id,
        title: 'Burj Khalifa at Night',
        note: 'Watching the Dubai Fountain show from the 148th floor of Burj Khalifa was surreal. The city lights stretching to the horizon make you feel on top of the world.',
        location: { lat: 25.1972, lng: 55.2744, name: 'Burj Khalifa', country: 'United Arab Emirates' },
        mood: 'amazing',
        weather: { temp: 30, description: 'Clear Night', icon: '01n' },
        photos: [{ url: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c', caption: 'Dubai skyline from above' }],
        distanceTraveled: 20,
      },
    ]);
    console.log('--- 11 JOURNAL ENTRIES CREATED ---');

    // =============================================
    // 4. Create Favorites (12+ favorites)
    // =============================================
    await Favorite.create([
      // Marcus's favorites
      {
        userId: marcus._id, type: 'restaurant', name: 'Sushisamba',
        address: 'Bishopsgate, London, UK', rating: 4.7,
        imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c',
        location: { lat: 51.5204, lng: -0.0794 },
      },
      {
        userId: marcus._id, type: 'attraction', name: 'Eiffel Tower',
        address: 'Champ de Mars, Paris, France', rating: 4.8,
        imageUrl: 'https://images.unsplash.com/photo-1511739001486-6bfe10ce785f',
        location: { lat: 48.8584, lng: 2.2945 },
      },
      {
        userId: marcus._id, type: 'hotel', name: 'Marina Bay Sands',
        address: '10 Bayfront Avenue, Singapore', rating: 4.9,
        imageUrl: 'https://images.unsplash.com/photo-1502722823883-da093f71db3a',
        location: { lat: 1.2834, lng: 103.8607 },
      },
      {
        userId: marcus._id, type: 'restaurant', name: 'Ramen Ichiraku',
        address: 'Shinjuku, Tokyo, Japan', rating: 4.6,
        imageUrl: 'https://images.unsplash.com/photo-1557872943-16a5ac26437e',
        location: { lat: 35.6938, lng: 139.7034 },
      },
      {
        userId: marcus._id, type: 'attraction', name: 'Sydney Opera House',
        address: 'Bennelong Point, Sydney, Australia', rating: 4.8,
        imageUrl: 'https://images.unsplash.com/photo-1624138784614-87fd1b6528f8',
        location: { lat: -33.8568, lng: 151.2153 },
      },
      {
        userId: marcus._id, type: 'hotel', name: 'Aman Tokyo',
        address: 'Otemachi Tower, Tokyo, Japan', rating: 4.9,
        imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945',
        location: { lat: 35.6866, lng: 139.7640 },
      },
      {
        userId: marcus._id, type: 'attraction', name: 'Tegallalang Rice Terrace',
        address: 'Ubud, Bali, Indonesia', rating: 4.7,
        imageUrl: 'https://images.unsplash.com/photo-1531973576160-7125cd663d86',
        location: { lat: -8.4312, lng: 115.2798 },
      },

      // Sarah's favorites
      {
        userId: sarah._id, type: 'restaurant', name: 'Le Jules Verne',
        address: 'Eiffel Tower, Paris, France', rating: 4.5,
        imageUrl: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0',
        location: { lat: 48.8584, lng: 2.2945 },
      },
      {
        userId: sarah._id, type: 'hotel', name: 'The Ritz London',
        address: '150 Piccadilly, London, UK', rating: 4.8,
        imageUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945',
        location: { lat: 51.5074, lng: -0.1416 },
      },

      // Alex's favorites
      {
        userId: alex._id, type: 'attraction', name: 'Colosseum',
        address: 'Piazza del Colosseo, Rome, Italy', rating: 4.9,
        imageUrl: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5',
        location: { lat: 41.8902, lng: 12.4922 },
      },
      {
        userId: alex._id, type: 'restaurant', name: 'La Boqueria Market',
        address: 'La Rambla, Barcelona, Spain', rating: 4.6,
        imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1',
        location: { lat: 41.3818, lng: 2.1714 },
      },

      // Priya's favorites
      {
        userId: priya._id, type: 'attraction', name: 'Gardens by the Bay',
        address: '18 Marina Gardens Dr, Singapore', rating: 4.7,
        imageUrl: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd',
        location: { lat: 1.2816, lng: 103.8636 },
      },
    ]);
    console.log('--- 12 FAVORITES CREATED ---');

    console.log('\n===========================================');
    console.log('  ✅ ALL DATA SEEDED SUCCESSFULLY');
    console.log('===========================================');
    console.log(`  👤 Users:    ${users.length}`);
    console.log(`  ✈️  Trips:    ${trips.length}`);
    console.log(`  📓 Journals: 11`);
    console.log(`  ⭐ Favorites: 12`);
    console.log('===========================================');
    console.log('\n  Login credentials:');
    console.log('  Admin: admin@wayfarer.com / password123');
    console.log('  User:  user@wayfarer.com / password123');
    console.log('===========================================\n');

    process.exit(0);
  } catch (err) {
    if (err.errors) {
      Object.keys(err.errors).forEach(key => {
        console.error(`Validation Error on ${key}: ${err.errors[key].message}`);
      });
    } else {
      console.error('ERROR SEEDING DATA:', err);
    }
    process.exit(1);
  }
}

seed();
