const mongoose = require('mongoose');
const User = require('../models/User');
const Trip = require('../models/Trip');
const dotenv = require('dotenv');

dotenv.config();

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://127.0.0.1:27017/wayfarer';

async function seedSwissTrip() {
  try {
    await mongoose.connect(MONGODB_URI);
    console.log('Connected to MongoDB');

    // Find the primary user (Rayhan)
    const user = await User.findOne({ email: 'rayhan@wayfarer.com' });
    if (!user) {
      console.error('User rayhan@wayfarer.com not found. Please run seedDummy.js first.');
      process.exit(1);
    }

    // Clear existing trips (optional, but requested "remove existing")
    await Trip.deleteMany({ userId: user._id });
    console.log('Cleared existing trips for user');

    // Create the Swiss Trip
    const swissTrip = new Trip({
      userId: user._id,
      destination: 'Swiss Alps Expedition',
      countryCode: 'CH',
      countryName: 'Switzerland',
      startDate: new Date('2026-06-15'),
      endDate: new Date('2026-06-25'),
      partySize: 2,
      status: 'planning',
      coverImage: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=1200',
      notes: 'Summer hike across the Bernese Oberland. Remember to buy the Swiss Travel Pass!',
      destinationInfo: {
        currency: 'CHF',
        language: 'German, French, Italian',
        timezone: 'CET',
        capital: 'Bern',
        population: 8600000,
        flagUrl: 'https://flagcdn.com/w320/ch.png'
      },
      checklist: [
        { item: 'Buy Swiss Travel Pass', category: 'other', checked: false, autoGenerated: true },
        { item: 'Book mountain huts', category: 'documents', checked: true, autoGenerated: true },
        { item: 'Pack hiking boots', category: 'packing', checked: false, autoGenerated: true },
        { item: 'Download offline SwissTopo maps', category: 'packing', checked: false, autoGenerated: true }
      ],
      itinerary: [
        { title: 'Arrive in Zurich', time: '10:00', date: new Date('2026-06-15'), location: 'Zurich Airport', checked: false },
        { title: 'Train to Grindelwald', time: '14:00', date: new Date('2026-06-15'), location: 'Interlaken Ost', checked: false },
        { title: 'Jungfraujoch Sphinx Observatory', time: '09:00', date: new Date('2026-06-17'), location: 'Jungfraujoch', checked: false }
      ]
    });

    await swissTrip.save();
    console.log('Swiss Alps Expedition trip created successfully!');

    process.exit(0);
  } catch (err) {
    console.error('Error seeding Swiss trip:', err);
    process.exit(1);
  }
}

seedSwissTrip();
