const mongoose = require('mongoose');

const planningSchema = new mongoose.Schema({
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  destination: {
    type: String,
    required: [true, 'Destination is required'],
  },
  countryCode: {
    type: String,
    required: true,
  },
  countryName: {
    type: String,
    default: '',
  },
  startDate: {
    type: Date,
    required: [true, 'Start date is required'],
  },
  endDate: {
    type: Date,
    required: [true, 'End date is required'],
  },
  partySize: {
    type: Number,
    default: 1,
    min: 1,
  },
  coverImage: {
    type: String,
    default: '',
  },
  checklist: [{
    item: { type: String, required: true },
    category: { 
      type: String, 
      enum: ['visa', 'health', 'packing', 'finance', 'documents', 'other'],
      default: 'other' 
    },
    checked: { type: Boolean, default: false },
    autoGenerated: { type: Boolean, default: false },
  }],
  notes: {
    type: String,
    default: '',
  },
  status: {
    type: String,
    enum: ['planning', 'active', 'completed', 'cancelled'],
    default: 'planning',
  },
  itinerary: [{
    title: { type: String, required: true },
    time: { type: String },
    date: { type: Date },
    location: { type: String },
    checked: { type: Boolean, default: false },
  }],
  destinationInfo: {
    currency: String,
    language: String,
    timezone: String,
    capital: String,
    population: Number,
    flagUrl: String,
  },
}, {
  timestamps: true,
});

// Index for efficient querying
planningSchema.index({ userId: 1, status: 1 });
planningSchema.index({ startDate: 1 });

module.exports = mongoose.model('Planning', planningSchema);
