class TripModel {
  final String id;
  final String userId;
  final String destination;
  final String countryCode;
  final String countryName;
  final DateTime startDate;
  final DateTime endDate;
  final int partySize;
  final String coverImage;
  final List<ChecklistItem> checklist;
  final String notes;
  final String status;
  final TripBudget budget;
  final DestinationInfo? destinationInfo;
  final DateTime createdAt;

  TripModel({
    required this.id,
    required this.userId,
    required this.destination,
    required this.countryCode,
    this.countryName = '',
    required this.startDate,
    required this.endDate,
    this.partySize = 1,
    this.coverImage = '',
    this.checklist = const [],
    this.notes = '',
    this.status = 'planning',
    TripBudget? budget,
    this.destinationInfo,
    DateTime? createdAt,
  }) : budget = budget ?? TripBudget(),
       createdAt = createdAt ?? DateTime.now();

  int get durationDays => endDate.difference(startDate).inDays;
  bool get isActive => status == 'active';
  bool get isPlanning => status == 'planning';
  bool get isCompleted => status == 'completed';
  int get checklistProgress {
    if (checklist.isEmpty) return 0;
    final checked = checklist.where((c) => c.checked).length;
    return ((checked / checklist.length) * 100).round();
  }

  factory TripModel.fromJson(Map<String, dynamic> json) {
    return TripModel(
      id: json['_id'] ?? '',
      userId: json['userId'] ?? '',
      destination: json['destination'] ?? '',
      countryCode: json['countryCode'] ?? '',
      countryName: json['countryName'] ?? '',
      startDate: DateTime.parse(json['startDate']),
      endDate: DateTime.parse(json['endDate']),
      partySize: json['partySize'] ?? 1,
      coverImage: json['coverImage'] ?? '',
      checklist: (json['checklist'] as List<dynamic>?)
          ?.map((e) => ChecklistItem.fromJson(e))
          .toList() ?? [],
      notes: json['notes'] ?? '',
      status: json['status'] ?? 'planning',
      budget: json['budget'] != null ? TripBudget.fromJson(json['budget']) : TripBudget(),
      destinationInfo: json['destinationInfo'] != null
          ? DestinationInfo.fromJson(json['destinationInfo'])
          : null,
      createdAt: json['createdAt'] != null ? DateTime.parse(json['createdAt']) : DateTime.now(),
    );
  }

  Map<String, dynamic> toJson() => {
    'destination': destination,
    'countryCode': countryCode,
    'startDate': startDate.toIso8601String(),
    'endDate': endDate.toIso8601String(),
    'partySize': partySize,
    'notes': notes,
    'budget': budget.toJson(),
  };
}

class ChecklistItem {
  final String item;
  final String category;
  final bool checked;
  final bool autoGenerated;

  ChecklistItem({
    required this.item,
    this.category = 'other',
    this.checked = false,
    this.autoGenerated = false,
  });

  factory ChecklistItem.fromJson(Map<String, dynamic> json) {
    return ChecklistItem(
      item: json['item'] ?? '',
      category: json['category'] ?? 'other',
      checked: json['checked'] ?? false,
      autoGenerated: json['autoGenerated'] ?? false,
    );
  }
}

class TripBudget {
  final double amount;
  final String currency;

  TripBudget({this.amount = 0, this.currency = 'USD'});

  factory TripBudget.fromJson(Map<String, dynamic> json) {
    return TripBudget(
      amount: (json['amount'] ?? 0).toDouble(),
      currency: json['currency'] ?? 'USD',
    );
  }

  Map<String, dynamic> toJson() => {'amount': amount, 'currency': currency};
}

class DestinationInfo {
  final String currency;
  final String language;
  final String timezone;
  final String capital;
  final int population;
  final String flagUrl;

  DestinationInfo({
    this.currency = '',
    this.language = '',
    this.timezone = '',
    this.capital = '',
    this.population = 0,
    this.flagUrl = '',
  });

  factory DestinationInfo.fromJson(Map<String, dynamic> json) {
    return DestinationInfo(
      currency: json['currency'] ?? '',
      language: json['language'] ?? '',
      timezone: json['timezone'] ?? '',
      capital: json['capital'] ?? '',
      population: json['population'] ?? 0,
      flagUrl: json['flagUrl'] ?? '',
    );
  }
}
